blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("search/<str:q>/", views.PostSearch.as_view()),
    path("delete_comment/<int:pk>/", views.CommentDelete.as_view()),
    path("update_comment/<int:pk>/", views.CommentUpdate.as_view()),
    path("category/<str:slug>/", views.category_page),
    path("delete_post/<int:pk>/", views.PostDelete.as_view(), name="post_delete"),
    path("update_post/<int:pk>/", views.PostUpdate.as_view()),
    path("create_post/", views.PostCreate.as_view()),
    path("<int:pk>/new_comment/", views.CommentCreate.as_view()),
    path("<int:pk>/", views.PostDetail.as_view()),
    path("", views.PostList.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("markdownx/", include("markdownx.urls")),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/', include('accounts.urls')),
    path("accounts/", include("allauth.urls")),
    path("", include("home_page.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
from datetime import timedelta


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/category/{self.slug}/"

    class Meta:
        verbose_name_plural = "Categories"


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = MarkdownxField()

    head_image = models.ImageField(upload_to="blog/images/%Y/%m/%d", blank=True)
    file_upload = models.FileField(upload_to="blog/files/%Y/%m/%d", blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
    )

    hit = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"[{self.pk}]{self.title} :: {self.author}"

    def get_absolute_url(self):
        return f"/blog/{self.pk}"

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split(".")[-1]

    def get_content_markdown(self):
        return markdown(self.content)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f"https://doitdjango.com/avatar/id/2636/fda31ee6d2cdedae/svg/{self.author.email}/"

    @property
    def update_counter(self):
        self.hit = self.hit + 1
        self.save()
        return self.hit


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.author}::{self.content}"

    def get_absolute_url(self):
        return f"{self.post.get_absolute_url()}#comment-{self.pk}"

    def is_updated(self):
        return self.updated_at - self.created_at > timedelta(seconds=1)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f"https://doitdjango.com/avatar/id/2636/fda31ee6d2cdedae/svg/{self.author.email}/"

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Category, Comment
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from .forms import CommentForm
from django.db.models import Q


class PostList(ListView):
    model = Post
    ordering = "-pk"
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context["categories"] = Category.objects.all()
        context["no_category_post_count"] = Post.objects.filter(category=None).count()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context["categories"] = Category.objects.all()
        context["no_category_post_count"] = Post.objects.filter(category=None).count()
        context["comment_form"] = CommentForm
        return context


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ["title", "content", "head_image", "file_upload", "category"]

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect("/blog/")


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ["title", "content", "head_image", "file_upload", "category"]
    template_name = "blog/post_update_form.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs["q"]
        post_list = Post.objects.filter(Q(title__contains=q)).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs["q"]
        context["search_info"] = f"Search: {q} ({self.get_queryset().count()})"

        return context


class PostDelete(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs["pk"])  # Comment -> Post로 변경

        if request.user == post.author:
            post.delete()
            # 삭제 후 메시지를 보여주는 템플릿으로 이동
            return render(request, "blog/post_confirm_delete.html")
        else:
            raise PermissionDenied

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs["pk"])  # Comment -> Post로 변경
        if request.user == post.author:
            post.delete()
            # 삭제 후 메시지를 보여주는 템플릿으로 이동
            return render(request, "blog/post_confirm_delete.html")
        else:
            raise PermissionDenied


def category_page(request, slug):
    if slug == "no_category":
        category = "미분류"
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        "blog/post_list.html",
        {
            "post_list": post_list,
            "categories": Category.objects.all(),
            "no_category_post_count": Post.objects.filter(category=None).count(),
            "category": category,
        },
    )


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        # post 객체 가져오기
        self.object = form.save(commit=False)
        self.object.post = get_object_or_404(Post, pk=self.kwargs["pk"])
        self.object.author = self.request.user
        return super().form_valid(form)


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class CommentDelete(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs["pk"])

        if request.user == comment.author:
            post_url = comment.post.get_absolute_url()
            comment.delete()
            return redirect(post_url)
        else:
            raise PermissionDenied

    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs["pk"])
        if request.user == comment.author:
            post_url = comment.post.get_absolute_url()
            comment.delete()
            return redirect(post_url)
        else:
            raise PermissionDenied

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} Blog {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}">
    <!--    <link rel="stylesheet" href="./practice.css" type="text/css">-->
    <script src="https://kit.fontawesome.com/5584f13f2e.js" crossorigin="anonymous"></script>
</head>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<body>
{% include 'blog/navbar.html' %}

<div class="container">
    <div class="row my-3">
        <div class="col-md-8 col-lg-9" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>

    <!-- Side widgets-->
        <div class="col-md-4 col-lg-3">
            <!-- Search widget-->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Search for..." id="search-input" />
                        <span class="input-group-append">
                            <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card" id='categories-card' style="max-width: 18rem;">
                <div class="card-header">Categories</div>
                <div class="card-body p-0">  <!-- padding 제거 -->
                    <div class="row m-0">     <!-- margin 제거 -->
                        <div class="col-lg-12 p-0">  <!-- padding 제거 -->
                            <ul class="list-group list-group-flush">
                                {% for category in categories %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <a href="{{ category.get_absolute_url }}" class="text-decoration-none w-100 text-dark">
                                        {{ category.name }} ({{ category.post_set.count }})
                                    </a>
                                </li>
                                {% endfor %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <a href="/blog/category/no_category/" class="text-decoration-none w-100 text-dark">
                                        미분류 ({{ no_category_post_count }})
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function searchPost(){
        let searchValue = document.getElementById('search-input').value.trim();
        if (searchValue.length > 1){
            location.href="/blog/search/" + searchValue + "/";
        }
        else {
            alert('검색어(' + searchValue + ')가 너무 짧습니다.');
        }
    };

    document.getElementById('search-input').addEventListener('keyup', function(event){
        if(event.key == 'Enter'){
            searchPost();
        }
    })
</script>

{% include 'blog/footer.html'%}

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} Blog {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}">
    <!--    <link rel="stylesheet" href="./practice.css" type="text/css">-->
    <script src="https://kit.fontawesome.com/5584f13f2e.js" crossorigin="anonymous"></script>
</head>
<body>
{% include 'blog/navbar.html' %}

<div class="container">
    <div class="row my-3">
        <div class="col-12" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>
    </div>
</div>

{% include 'blog/footer.html'%}


<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
<H1>Edit Comment</H1>
<hr>
<form method="post" id="comment-form">{% csrf_token %}
    {{ form | crispy }}
    <br>
    <button type="submit" class="btn btn-primary float-end">Submit</button>
</form>

{% endblock %}

blog/templates/blog/footer.html
<footer class="py-3 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Blog 2025</p></div>
</footer>

blog/templates/blog/navbar.html
{% load socialaccount %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand text-white" href="/" white >Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="/blog/">Home</a>
        </li>
      </ul>

        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.socialaccount_set.first.get_avatar_url  %}
                    <img class="rounded-circle" width="25px"
                         src="{{ user.socialaccount_set.first.get_avatar_url  }}"
                         alt="{{ user.username }}">
                    {% else %}
                    <img class="rounded-circle" width="25px"
                         src="https://doitdjango.com/avatar/id/2636/fda31ee6d2cdedae/svg/{{ user.email }}/"
                         alt="{{ user.username }}">
                    {% endif %}
                    &nbsp;
                    {{ user.username }}
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/accounts/logout/">Log Out</a></li>
                </ul>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#LoginModal" class="text-white">Log In</a>
            </li>
            {% endif %}
        </ul>

    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="LoginModal" tabindex="-1" aria-labelledby="LoginModalLabel" aria-hidden="true" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="loginModalLabel"><i class="fa-solid fa-right-to-bracket"></i>Log In</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="d-grid gap-2">
                        <a role="button" href="{% provider_login_url 'google' %}" type="button" class="btn btn-outline-dark"><i class="fa-brands fa-google"></i> Log In With Google</a>
                        <a role="button" href="{% provider_login_url 'kakao' %}" type="button" class="btn btn-outline-dark"><i class="fa-solid fa-comment"></i> Log In With Kakao</a>
                        <a role="button" href="/accounts/login/" class="btn btn-outline-dark"><i class="fa-regular fa-user"></i> Log In With User Name</a>
                        <a role="button" href="/accounts/signup/" type="button" class="btn btn-outline-dark"><i class="fa-regular fa-envelope"></i> Sign Up With E-mail</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block main_area %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">존재하지 않는 게시글입니다</h4>
                <hr>
                <a href="/blog/" class="btn btn-primary">글 목록으로 돌아가기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ post.title }} | Blog
{% endblock %}


{% block main_area %}

<!-- Post content-->
<div id="post-area">
    {% if post.category %}
    <span class="badge text-bg-secondary float-end">{{ post.category }}</span>
    {% else %}
    <span class="badge text-bg-secondary float-end">미분류</span>
    {% endif %}
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
            <!-- Post Delete Button -->


            <!-- Post content-->
            <div class="text-muted fst-italic mb-2">Posted on {{ post.created_at}} by
                <img class="mr-1 rounded-circle" src="{{ post.get_avatar_url }}" width="25px" alt="{{ post.author }}">
                <a href="#">{{ post.author | upper }}</a>
                <p> 조회수 : {{ post.update_counter }} </p>
            </div>

            {% if user.is_authenticated and user == post.author %}
            <div class="float-end">
                <a href="/blog/update_post/{{ post.pk }}" class="btn btn-outline-secondary btn-sm ms-2">
                    <i class="fa-solid fa-pen"></i> Edit Post
                </a>
                <a href="/blog/delete_post/{{ post.pk }}" class="btn btn-outline-danger btn-sm">
                    Delete Post
                </a>
            </div>
            {% endif %}
        </header>

        <br>
        <br>
        <!-- Preview image figure-->
        {% if post.head_image %}
        <figure class="mb-4"><img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }}" /></figure>
        {% else %}
        <img class="card-img-top" src="https://picsum.photos/seed/{{ post.id }}/600/200" alt="{{ p.title }}" />
        {% endif %}
        <!-- Post content-->
        <section class="mb-5">
            <p> {{ post.get_content_markdown | safe }} </p>
        </section>


        {% if post.file_upload %}
        <a href="{{ post.file_upload.url }}" type="button" class="btn btn-outline-dark" role="button" download>
            Download :
            {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
            <i class="fa-regular fa-file-excel"></i>
            {% elif post.get_file_ext == 'csv' %}
            <i class="fa-solid fa-file-csv"></i>
            {% elif post.get_file_ext == 'docx' %}
            <i class="fa-regular fa-file-word"></i>
            {% elif post.get_file_ext == 'pdf' %}
            <i class="fa-regular fa-file-pdf"></i>
            {% else %}
            <i class="fa-regular fa-file-lines"></i>
            {% endif %}

            {{ post.get_file_name }}
        </a>
        {% endif%}

    </article>
    <hr>
</div>

<div id="comment-area">
    <!-- comment form   -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            {% if user.is_authenticated %}
            <form id="comment-form" method="post" action="{{ post.get_absolute_url }}/new_comment/">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form | crispy }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
                <a role="button" type="button" class="btn btn-outline-dark w-100" href="#" data-bs-toggle="modal" data-bs-target="#LoginModal">Log In and Leave a Comment</a>
            {% endif %}
        </div>
    </div>
{% if post.comment_set.exists %}
    {% for comment in post.comment_set.iterator %}
    <!-- Single comment-->
    <div class="d-flex" id="comment-{{ comment.pk }}">
        <div class="flex-shrink-0">
            <img class="rounded-circle" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}" width="50px"/>
        </div>
        <div class="flex-grow-1 ms-3">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <h5 class="mb-0">{{ comment.author.username }}</h5>
                    <small class="text-muted ms-2">{{ comment.created_at }}</small>
                </div>
                {% if user.is_authenticated and comment.author == user %}
                <div class="flaot-end">
                    <a class="btn btn-sm btn-outline-primary" role="button" href="/blog/update_comment/{{ comment.pk }}/"
                       id="comment-{{ comment.pk }}-update-btn">
                        Edit
                    </a>
                    <a class="btn btn-sm btn-outline-danger" role="button" href="#" id="comment-{{ comment.pk }}-delete-btn"
                       data-bs-toggle="modal" data-bs-target="#deleteCommentModal-{{ comment.pk }}">
                        Delete
                    </a>
                </div>
                <!-- Modal {{comment.pk }} -->
                <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" aria-labelledby="DeleteCommentModal-{{ comment.pk }}-ModalLabel" aria-hidden="true" >
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="DeleteCommentModalLabel-{{ comment.pk }}">Are You Sure?</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <del> {{ comment.content | linebreaks }} </del>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a role="button" type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</a>
                                <a role="button" type="button" class="btn btn-outline-danger" href="/blog/delete_comment/{{ comment.pk }}/">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>

                {% endif %}
            </div>
            {{ comment.content | linebreaks }}
            {% if comment.is_updated %}
            <small class="text-muted float-end"> Updated: {{ comment.updated_at }} </small>
            {% endif %}
        </div>
    </div>
    {% endfor %}
{% endif %}

</div>



{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title%} Create Post {% endblock %}

{% block main_area %}
<h1>Creat Post</h1>
<hr>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ form | crispy }}
    </table>
    <button type="submit" class="btn btn-dark float-end">Submit</button>
</form>
{{ form.media }}
<br>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}
{% if user.is_authenticated %}
{% if user.is_superuser or user.is_staff %}
<a type="button" href="/blog/create_post/" class="btn btn-outline-dark btn-sm float-end"><i class="fa-solid fa-pen"></i> New Post </a>
{% endif %}
{% endif %}
<h1>
    Blog
    {% if search_info %} <small class="text-muted"> {{ search_info }} </small> {% endif %}
    {% if category %}
    <h4><span class="badge rounded-pill text-bg-dark float-end">{{ category }}</span></h4>
    {% endif %}
    <br>
    <br>
</h1>
{% if post_list.exists %}
<div class="container">
    <div class="row">
        {% for p in post_list %}
        <div class="col-md-6 mb-4">
            <div class="card h-100">
                <a href="{{ p.get_absolute_url }}">
                    {% if p.head_image %}
                    <a href="#!"><img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p.title }}" style="width: 100%; height: 350px; object-fit: cover;" /></a>
                    {% else %}
                    <a href="#!"><img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/200/300" alt="{{ p.title }}" style="width: 100%; height: 350px; margin: 0 auto; display: block;"/></a>
                    {% endif %}
                </a>
                <div class="card-body">
                    <h2 class="card-title h4">{{ p.title }}</h2>
                    <div class="small text-muted">Posted on {{ p.created_at|date:"F j, Y" }}
                        by
                        <img class="mr-1 rounded-circle" src="{{ p.get_avatar_url }}" width="25px" alt="{{ post.author }}">
                        {{ p.author|upper }}
                    </div>
                    <p class="card-text">{{ p.get_content_markdown | truncatewords_html:45 | safe }}</p>
                    <a class="btn btn-dark text-white" href="{{ p.get_absolute_url }}">Read more →</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% else %}
<h1>아직 게시물이 없습니다.</h1>
{% endif %}

{% if is_paginated %}
<!-- Pagination -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <nav aria-label="Pagination">
                <hr class="my-0" />
                <ul class="pagination justify-content-center my-4">
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><- Older</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#"><- Older</a>
                    </li>
                    {% endif %}

                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer -></a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Newer -></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title%} Edit Post {% endblock %}

{% block main_area %}
    <h1>Edit</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>
        <button type="submit" class="btn btn-dark"> Submit </button>
    </form>

{% endblock %}